/**
 * Login Constants 
 */
export const LOGIN = 'LOGIN';

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT        = 'LOGOUT'

/**
 * Assignment Constants 
 */
export const GET_ALL_ASSIGNMENTS = 'GET_ALL_ASSIGNMENTS';
export const GET_ASSIGNMENT_BY_ID = 'GET_ASSIGNMENT_BY_ID';
export const GET_ASSIGNMENT_EMPLOYEES = 'GET_ASSIGNMENT_EMPLOYEES';
export const ADD_ASSIGNMENT     = 'ADD_ASSIGNMENT';
export const REMOVE_ASSIGNMENT  = 'REMOVE_ASSIGNMENT';
export const UPDATE_ASSIGNMENT  = 'UPDATE_ASSIGNMENT';

/**
 * Employee Constants 
 */
export const GET_ALL_EMPLOYEES   = 'GET_ALL_EMPLOYEES';
export const ADD_EMPLOYEE       = 'ADD_EMPLOYEE';
export const REMOVE_EMPLOYEE    = 'REMOVE_EMPLOYEE';
export const UPDATE_EMPLOYEE    = 'UPDATE_EMPLOYEE';


/**
 * Project Constants 
 */
export const GET_ALL_PROJECTS   = 'GET_ALL_PROJECTS';
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID';
export const GET_EMPLOYEES_IN_PROJECT = 'GET_EMPLOYEES_IN_PROJECT';
export const GET_ASSIGNMENTS_IN_PROJECT = 'GET_ASSIGNMENTS_IN_PROJECT';
export const ADD_PROJECT       = 'ADD_PROJECT';
export const REMOVE_PROJECT    = 'REMOVE_PROJECT';
export const UPDATE_PROJECT    = 'UPDATE_PROJECT';
export const GET_ALL_PROJECT_ROLES = 'GET_ALL_PROJECT_ROLES';
export const UPDATE_PROJECT_ROLES = 'UPDATE_PROJECT_ROLES';
export const REMOVE_PROJECT_ROLES = 'REMOVE_PROJECT_ROLES';