/**
 * Login Constants
 */
export const LOGIN = "LOGIN";

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT        = 'LOGOUT'

/**
 * Assignment Constants
 */
export const GET_ALL_ASSIGNMENTS = "GET_ALL_ASSIGNMENTS";
export const GET_ALL_ASSIGNMENTS_REVERSED = "GET_ALL_ASSIGNMENTS_REVERSED";
export const GET_ASSIGNMENT_BY_ID = "GET_ASSIGNMENT_BY_ID";
export const GET_ASSIGNMENT_EMPLOYEES = "GET_ASSIGNMENT_EMPLOYEES";
export const GET_ASSIGNMENT_STATUS = 'GET_ASSIGNMENT_STATUS';
export const GET_ALL_BLOCKED_ASSIGNMENTS = 'GET_ALL_BLOCKED_ASSIGNMENTS';
export const ADD_ASSIGNMENT = "ADD_ASSIGNMENT";
export const ADD_EMPLOYEE_TO_ASSIGNMENT = 'ADD_EMPLOYEE_TO_ASSIGNMENT';
export const REMOVE_ASSIGNMENT = "REMOVE_ASSIGNMENT";
export const REMOVE_PROJECT_ASSIGNMENT = 'REMOVE_PROJECT_ASSIGNMENT';
export const REMOVE_EMPLOYEE_FROM_PROJECT = 'REMOVE_EMPLOYEE_FROM_PROJECT';
export const UPDATE_ASSIGNMENT = "UPDATE_ASSIGNMENT";
export const IN_ORDER          = "IN_ORDER";
export const RECENT_ORDER      = "RECENT_ORDER";
export const NEED_ATTENTION    = 'NEED_ATTENTION';
/**
 * Employee Constants
 */
export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID";
export const GET_ALL_EMPLOYEE_TO_ASSIGNMENT = "GET_ALL_EMPLOYEE_TO_ASSIGNMENT";
export const GET_ALL_EMPLOYEE_ASSIGNMENTS = "GET_ALL_EMPLOYEE_ASSIGNMENTS";
export const SEARCH_EMPLOYEES   = 'SEARCH_EMPLOYEES';

/**
 * Project Constants
 */
export const GET_ALL_PROJECTS   = 'GET_ALL_PROJECTS';
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID';
export const GET_EMPLOYEES_IN_PROJECT = 'GET_EMPLOYEES_IN_PROJECT';
export const GET_ASSIGNMENTS_IN_PROJECT = 'GET_ASSIGNMENTS_IN_PROJECT';
export const ADD_PROJECT       = 'ADD_PROJECT';
export const ADD_PROJECT_ROLE  = 'ADD_PROJECT_ROLE'
export const REMOVE_PROJECT    = 'REMOVE_PROJECT';
export const UPDATE_PROJECT    = 'UPDATE_PROJECT';
export const GET_ALL_PROJECT_ROLES = 'GET_ALL_PROJECT_ROLES';
export const UPDATE_PROJECT_ROLES = 'UPDATE_PROJECT_ROLES';
export const REMOVE_PROJECT_ROLES = 'REMOVE_PROJECT_ROLES';
